### ISSUE TITLE
Build libbpf/scr fails

### ISSUE THREAD

**Issue by sherwoodzern** [lizrice/learning-ebpf#10]
I execute make install in the libbpf/src directory and it fails with the following issue. What am I doing incorrectly?

INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
install: cannot change permissions of ‘/usr/include/bpf’: No such file or directory
make: *** [Makefile:157: install_headers] Error 1

**Comment by lizrice** [comment]
You'll need to be running as root / sudo for the install part to work. Please feel free to re-open this issue if that isn't the problem
