### ISSUE TITLE
Chapter 7 - link is broken 

### ISSUE THREAD

**Issue by sherwoodzern** [lizrice/learning-ebpf#18]
To dive into the details of the context data passed to different BPF
program types, check out this post by Alan Maguire on Oracle’s
blog.

The provided link points to https://elixir.bootlin.com/linux/v5.19.14/source/include/uapi/linux/bpf.h

**Comment by sherwoodzern** [comment]
The correct link should be https://blogs.oracle.com/linux/post/bpf-a-tour-of-program-types

**Comment by lizrice** [comment]
Thanks, I've filed that update with O'Reilly's errata process
