### ISSUE TITLE
chapter8 pingpong example code 

### ISSUE THREAD

**Issue by Cyc1ing1313** [lizrice/learning-ebpf#9]
I created two veth,i attached this bpf program to egress direction on veth0,and when i ping to veth1 from veth0,the vm crash.could you explain why it's only working in ingress direction?

**Comment by lizrice** [comment]
Can you send some information about what you see in the "crash"? Do you get a stack trace?

**Comment by lizrice** [comment]
Closing as stale, please reopen if you have more information
